"""Pydantic schemas for Protocol Assistant API."""

from app.schemas.chat import (
    ChatMessageRequest,
    ChatMessageResponse,
    ChatResponse,
    MessageType,
    SessionCreateRequest,
    SessionHistoryResponse,
    SessionResponse,
    SessionUpdateRequest,
    StreamingChatRequest,
)
from app.schemas.document import (
    DocumentSection,
    ParsedDocument,
    DocumentParseRequest,
    DocumentParseResponse,
    PHIDetectionResult,
)
from app.schemas.protocol import (
    StudyType,
    ExtractedObjectives,
    ExtractedMethodology,
    ExtractedDataCollection,
    ExtractedRisksBenefits,
    ExtractedProtocol,
    GapQuestion,
    GapAnalysisResult,
    ProtocolExtractionRequest,
    ProtocolExtractionResponse,
    ProtocolQualityAssessment,
)
from app.schemas.generation import (
    DocumentType,
    GenerateRequest,
    AbstractSchema,
    ConsentFormSchema,
    ProtocolDocumentSchema,
    RecruitmentMaterialsSchema,
    DataManagementPlanSchema,
    GeneratedDocument,
    GeneratedFormInstance,
    PrefillRequest,
    PrefillResponse,
    BulkGenerationRequest,
    BulkGenerationResponse,
    GenerationStatus,
    GenerationJobStatus,
)
from app.schemas.wizard import (
    AnswerSource,
    FormFieldInfo,
    SuggestedAnswer,
    EnhancedGapQuestion,
    SectionInfo,
    WizardQuestionsResponse,
    AnswerRequest,
    AnswerResponse,
    SkipResponse,
    WizardProgress,
)

__all__ = [
    # Chat schemas
    "MessageType",
    "ChatMessageRequest",
    "ChatMessageResponse",
    "ChatResponse",
    "SessionCreateRequest",
    "SessionResponse",
    "SessionHistoryResponse",
    "SessionUpdateRequest",
    "StreamingChatRequest",
    # Document schemas
    "DocumentSection",
    "ParsedDocument",
    "DocumentParseRequest",
    "DocumentParseResponse",
    "PHIDetectionResult",
    # Protocol schemas
    "StudyType",
    "ExtractedObjectives",
    "ExtractedMethodology",
    "ExtractedDataCollection",
    "ExtractedRisksBenefits",
    "ExtractedProtocol",
    "GapQuestion",
    "GapAnalysisResult",
    "ProtocolExtractionRequest",
    "ProtocolExtractionResponse",
    "ProtocolQualityAssessment",
    # Generation schemas
    "DocumentType",
    "GenerateRequest",
    "AbstractSchema",
    "ConsentFormSchema",
    "ProtocolDocumentSchema",
    "RecruitmentMaterialsSchema",
    "DataManagementPlanSchema",
    "GeneratedDocument",
    "GeneratedFormInstance",
    "PrefillRequest",
    "PrefillResponse",
    "BulkGenerationRequest",
    "BulkGenerationResponse",
    "GenerationStatus",
    "GenerationJobStatus",
    # Wizard schemas
    "AnswerSource",
    "FormFieldInfo",
    "SuggestedAnswer",
    "EnhancedGapQuestion",
    "SectionInfo",
    "WizardQuestionsResponse",
    "AnswerRequest",
    "AnswerResponse",
    "SkipResponse",
    "WizardProgress",
]
