import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { Sparkles, FileText, Brain, Users } from 'lucide-react';
import { cn } from '@/lib/utils';

interface SuggestionBadgeProps {
  source?: string;
  confidence?: number;
  className?: string;
}

const sourceConfig: Record<string, { icon: React.ElementType; label: string; color: string }> = {
  document: { icon: FileText, label: 'From Document', color: 'bg-blue-100 text-blue-800 border-blue-200' },
  ai: { icon: Brain, label: 'AI Generated', color: 'bg-purple-100 text-purple-800 border-purple-200' },
  learned: { icon: Users, label: 'Learned Pattern', color: 'bg-green-100 text-green-800 border-green-200' },
  common: { icon: Sparkles, label: 'Common Value', color: 'bg-amber-100 text-amber-800 border-amber-200' },
};

export function SuggestionBadge({ source = 'ai', confidence, className }: SuggestionBadgeProps) {
  const config = sourceConfig[source] || sourceConfig.ai;
  const Icon = config.icon;

  const confidenceLabel = confidence !== undefined
    ? confidence >= 0.8 ? 'High confidence'
    : confidence >= 0.5 ? 'Medium confidence'
    : 'Low confidence'
    : null;

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className="inline-flex">
            <Badge
              variant="outline"
              className={cn(
                'gap-1 text-xs font-normal cursor-help',
                config.color,
                className
              )}
            >
              <Icon className="h-3 w-3" />
              {config.label}
            </Badge>
          </span>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs">
          <p className="text-sm">
            {source === 'document' && 'This suggestion was extracted from an uploaded document.'}
            {source === 'ai' && 'This suggestion was generated by AI based on context.'}
            {source === 'learned' && 'This value was learned from previous projects or corrections.'}
            {source === 'common' && 'This is a commonly used value for this type of field.'}
          </p>
          {confidenceLabel && (
            <p className="text-xs text-muted-foreground mt-1">{confidenceLabel}</p>
          )}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
